---
- name: Cập nhật apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Cài đặt các gói tiện ích
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
      - python3-pip
    state: present

- name: Cài đặt gói Python Docker
  pip:
    name:
      - docker
      - docker-compose
    state: present