---
- name: Tạo thư mục cho Prometheus
  file:
    path: "/opt/prometheus"
    state: directory
    mode: '0755'

- name: Sao chép file cấu hình Prometheus
  template:
    src: "{{ playbook_dir }}/roles/prometheus/templates/prometheus.yml.j2"
    dest: "/opt/prometheus/prometheus.yml"
    mode: '0644'

- name: Chạy Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

- name: Chạy Node Exporter container
  docker_container:
    name: node-exporter
    image: prom/node-exporter
    state: started
    restart_policy: always
    ports:
      - "9100:9100"