all:
  hosts:
    app_server:
      ansible_host: 192.168.1.10
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    monitoring_server:
      ansible_host: 192.168.1.11
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  
  children:
    app:
      hosts:
        app_server:
    monitoring:
      hosts:
        monitoring_server: