---
- name: Cài đặt các thành phần chung
  hosts: all
  become: yes
  roles:
    - common
    - docker

- name: Triển khai ứng dụng Go
  hosts: app
  become: yes
  roles:
    - app

- name: Triển khai hệ thống giám sát
  hosts: monitoring
  become: yes
  roles:
    - prometheus
    - grafana